-- ==============================================================================
-- CaseLedger AI: Snowflake DDL Definitions (Executed via Snowflake CoCo CLI)
-- Command: coco sql --file ddl/01_aml_schema.sql
-- ==============================================================================

CREATE DATABASE IF NOT EXISTS CASELEDGER_DB;
CREATE SCHEMA IF NOT EXISTS CASELEDGER_DB.AML_CORE;
USE SCHEMA CASELEDGER_DB.AML_CORE;

-- 1. Subject & Counterparty Accounts Table
CREATE OR REPLACE TABLE ACCOUNTS (
    ACCOUNT_ID VARCHAR(32) PRIMARY KEY,
    HOLDER_NAME VARCHAR(256) NOT NULL,
    RISK_SCORE NUMBER(3,0) DEFAULT 50,
    RISK_TIER VARCHAR(16) DEFAULT 'MEDIUM',
    ACCOUNT_TYPE VARCHAR(32),
    BRANCH_ID VARCHAR(32),
    BRANCH_NAME VARCHAR(128),
    PRIMARY_DEVICE_ID VARCHAR(64),
    KYC_STATUS VARCHAR(32),
    ANNUAL_TURNOVER NUMBER(18,2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Transaction Ledger with CTR & Structuring Flags
CREATE OR REPLACE TABLE TRANSACTIONS (
    TRANSACTION_ID VARCHAR(64) PRIMARY KEY,
    SOURCE_ACCOUNT_ID VARCHAR(32) REFERENCES ACCOUNTS(ACCOUNT_ID),
    COUNTERPARTY_ACCOUNT_ID VARCHAR(32),
    COUNTERPARTY_NAME VARCHAR(256),
    TRANSACTION_TYPE VARCHAR(16), -- CREDIT, DEBIT
    CHANNEL VARCHAR(32), -- CASH_BRANCH, IMPS, RTGS, UPI, NEFT
    AMOUNT NUMBER(18,2) NOT NULL,
    CTR_PROXIMITY NUMBER(5,4), -- percentage of 10L threshold (0.95 = 95%)
    IS_FLAGGED BOOLEAN DEFAULT FALSE,
    FLAG_REASON VARCHAR(256),
    DEVICE_ID VARCHAR(64),
    IP_ADDRESS VARCHAR(64),
    EXECUTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Governed Evidence Matrix Table (Supporting vs Mitigating)
CREATE OR REPLACE TABLE EVIDENCE_RECORDS (
    EVIDENCE_ID VARCHAR(32) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(32) REFERENCES ACCOUNTS(ACCOUNT_ID),
    CATEGORY VARCHAR(32) NOT NULL, -- SUPPORTING, CONTRADICTING, POLICY, MISSING
    TITLE VARCHAR(256) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    REFERENCE_ID VARCHAR(64),
    POLICY_CITATION VARCHAR(128),
    IS_PINNED BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(64) DEFAULT 'COCO_AML_AGENT',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Regulatory Corpus Table (For Cortex Search Service)
CREATE OR REPLACE TABLE REGULATORY_POLICY_CORPUS (
    POLICY_ID VARCHAR(32) PRIMARY KEY,
    POLICY_NAME VARCHAR(128) NOT NULL,
    SECTION VARCHAR(64) NOT NULL,
    REGULATORY_BODY VARCHAR(64) NOT NULL, -- FIU_IND, RBI, FATF
    VERSION VARCHAR(32) NOT NULL,
    SOURCE_DOCUMENT VARCHAR(128),
    POLICY_TEXT TEXT NOT NULL,
    RELEVANCE_CRITERIA TEXT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. Immutable Decision Replay & Audit Snapshot Table (Tamper-Sealed)
CREATE OR REPLACE TABLE DECISION_REPLAY_SNAPSHOTS (
    SNAPSHOT_ID VARCHAR(64) PRIMARY KEY,
    CASE_ID VARCHAR(32) NOT NULL,
    SUBJECT_ACCOUNT_ID VARCHAR(32) NOT NULL,
    DATA_FREEZE_CHECKSUM VARCHAR(128) NOT NULL, -- SHA-256
    ORIGINAL_AI_DRAFT TEXT NOT NULL,
    ANALYST_REFINED_FINDING TEXT NOT NULL,
    DISPOSITION VARCHAR(64) NOT NULL, -- RETURNED_RFI, ESCALATED_FIU, CLOSED_FALSE_POSITIVE
    REVIEWER_NOTES TEXT NOT NULL,
    REVIEWER_NAME VARCHAR(128) NOT NULL,
    RULE_ENGINE_VERSION VARCHAR(32) NOT NULL,
    POLICY_CORPUS_VERSION VARCHAR(32) NOT NULL,
    SNAPSHOT_METRICS VARIANT, -- JSON of velocity, structuring, device overlap
    SEALED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create Stage for Streamlit companion app
CREATE STAGE IF NOT EXISTS STREAMLIT_STAGE;
